name: Continuous Integration
on: push
jobs:
  unit-tests:
    uses: ./.github/workflows/_test.yml
  npm-publish:
    needs: unit-tests
    if: github.ref == 'refs/heads/master' && needs.unit-tests.result == 'success'
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          if [[ "${{ github.repository_owner }}" == "pelias" ]]; then
            curl "https://raw.githubusercontent.com/pelias/ci-tools/master/semantic-release.sh" | bash -
          fi
